name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
    
    - name: Initialize Go modules
      run: go mod tidy
    
    - name: Build
      run: go build -v ./...

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud config set project proven-fx-423903-k1
        gcloud functions deploy linkGCal \
        --runtime go121 \
        --trigger-http \
        --region asia-northeast3 \
        --allow-unauthenticated \
        --set-env-vars GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
